####################################################################################
#
# Generated by eda_pt_script.tcl	#1
#              eda_pt_conversion.tcl	#1
#              in c:/altera/91sp2/quartus/common/tcl/internal/eda_pt/.
#
# Quartus:  Version 9.1 Build 350 03/24/2010 Service Pack 2 SJ Web Edition
#
# Project:  relogio
# Revision: relogio
#
# Date: Sun Jun 02 12:18:17 -0300 2013
#
####################################################################################


set _col12 [ get_pins {P1|change.combout}]



set _col13 [ get_pins {P2|change2.combout}]



set _col0 [ get_ports {clk}]



set _col1 [ get_ports {clr}]



