LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

-- LIBRARY TRABALHO_CD2;
-- USE TRABALHO
-- USE TRABALHO.ULA_PACKAGE.ALL;

	



ENTITY ULA_1BIT IS
	PORT(A,B: IN BIT;
		 A_B_Cin: IN BIT_VECTOR(2 DOWNTO 0);
		 SEL_ULA: IN BIT_VECTOR (2 DOWNTO 0);
		 S_Cout0: OUT BIT;
		 S_Cout1: OUT BIT;
		 SAIDA_ULA: OUT BIT);
END ULA_1BIT;

ARCHITECTURE ESTRUTURAL OF ULA_1BIT IS
	COMPONENT DECODIFICADOR_3x8 IS
		PORT(SEL: BIT_VECTOR (2 DOWNTO 0);
			 S0,S1,S2,S3,S4,S5,S6,S7: OUT BIT);
	END COMPONENT;
	
	COMPONENT PORTAS_LOGICAS IS
		PORT(A,B: IN BIT;
			 COND_PORTA: IN BIT_VECTOR (2 DOWNTO 0); -- CONDIÇÕES
			 EP0,EP1,EP2,EP3,EP4,EP5,EP6,EP7: IN BIT;			 
			 S0,S1,S2,S3,S4,S5,S6,S7: OUT BIT);
	END COMPONENT;
	
	COMPONENT SOMADOR IS
		PORT (A_B_Cin: IN BIT_VECTOR (2 DOWNTO 0);
			  C_Out: OUT BIT;
		      S: OUT BIT);
	END COMPONENT;

	COMPONENT SUBTRATOR IS
		PORT(A_B_Cin: IN BIT_VECTOR (2 DOWNTO 0);
		     S: OUT BIT;
			 Cout: OUT BIT);
	END COMPONENT;
	
	COMPONENT OR_8 IS
		PORT(A,B,C,D,E,F,G,H: IN BIT;
			 S: OUT BIT);
	END COMPONENT;
	
	
SIGNAL T0,T1,T2,T3,T4,T5,T6,T7: BIT;
SIGNAL Z0,Z1,Z2,Z3,Z4,Z5,Z6,Z7: BIT; -- SAIDAS PARA AS PORTAS LÓGICAS
SIGNAL S_SOMA, S_SUB: BIT;

BEGIN	
		P1: DECODIFICADOR_3X8 PORT MAP (SEL_ULA,T0,T1,T2,T3,T4,T5);
		P2: SOMADOR PORT MAP (A_B_Cin,S_SOMA,S_Cout0);  -- entra 3 bits A,B e Cin em Somador sendo A(2) B(1) & Cin(0)
		P3: SUBTRATOR PORT MAP (A_B_Cin,S_SUB,S_Cout1);  -- entra 3 bits A,B e Cin em Somador sendo A(2) B(1) & Cin
		P4: PORTAS_LOGICAS PORT MAP (A,B,SEL_ULA,T0,T1,T2,T3,T4,T5,S_SOMA,S_SUB,Z0,Z1,Z2,Z3,Z4,Z5,Z6,Z7); -- A ATÉ S_SUB SÃO ENTRADAS, JÁ Z0 À Z7 SÃO SAIDAS
		P5: OR_8 PORT MAP (Z0,Z1,Z2,Z3,Z4,Z5,Z6,Z7,SAIDA_ULA);
END ESTRUTURAL;	