/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classificadordeseguros.AvaliacaoRegras;
import classificadordeseguros.Fuzzificacao;
import classificadordeseguros.Risco;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Suelen
 */
public class IntefaceClassificadorDeSeguros extends javax.swing.JFrame {

    /**
     * Creates new form IntefaceClassificadorDeIdades
     */
    public IntefaceClassificadorDeSeguros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enunciado1 = new javax.swing.JLabel();
        questao1 = new javax.swing.JLabel();
        idade = new javax.swing.JTextField();
        questao2 = new javax.swing.JLabel();
        velocidade = new javax.swing.JTextField();
        questao3 = new javax.swing.JLabel();
        acidentes = new javax.swing.JTextField();
        questao4 = new javax.swing.JLabel();
        experiencia = new javax.swing.JTextField();
        decidir = new javax.swing.JButton();
        resposta = new javax.swing.JLabel();
        lblidade = new javax.swing.JLabel();
        lblvelocidade = new javax.swing.JLabel();
        lblacidentes = new javax.swing.JLabel();
        lblexperiencia = new javax.swing.JLabel();
        enunciado2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para Seguros");

        enunciado1.setText("Responda as questões abaixo e, no final, o sistema retornará se");

        questao1.setText("Quantos anos tem o segurado?");

        questao2.setText("Qual a velocidade média que o segurado costuma dirigir na cidade?");

        questao3.setText("Qual a quantidade de acidentes anteriores do segurado?");

        questao4.setText("Qual o tempo de experiência do segurado? ");

        experiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experienciaActionPerformed(evt);
            }
        });

        decidir.setText("Decidir!");
        decidir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decidirActionPerformed(evt);
            }
        });

        resposta.setText("Assinar o contrato é:");

        lblidade.setText("anos.");

        lblvelocidade.setText("Km/h.");

        lblacidentes.setText("acidentes.");

        lblexperiencia.setText("anos.");

        enunciado2.setText(" é seguro ou arriscado para a seguradora assinar o contrato.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enunciado1)
                    .addComponent(enunciado2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblidade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(velocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvelocidade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acidentes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblacidentes))
                    .addComponent(questao1)
                    .addComponent(questao2)
                    .addComponent(questao3)
                    .addComponent(questao4)
                    .addComponent(resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblexperiencia)))
                .addGap(13, 13, 13))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(decidir, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enunciado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(questao1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(questao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(velocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvelocidade))
                .addGap(12, 12, 12)
                .addComponent(questao3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acidentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblacidentes))
                .addGap(13, 13, 13)
                .addComponent(questao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblexperiencia))
                .addGap(66, 66, 66)
                .addComponent(decidir)
                .addGap(51, 51, 51)
                .addComponent(resposta)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        enunciado1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void experienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_experienciaActionPerformed

    private void decidirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decidirActionPerformed
        if(idade.getText().isEmpty() || velocidade.getText().isEmpty() || acidentes.getText().isEmpty() || experiencia.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos");
        }else{
                
            Double fuzIdade = Double.parseDouble(idade.getText());
            Double fuzVelocidade = Double.parseDouble(velocidade.getText());
            Double fuzAcidentes = Double.parseDouble(acidentes.getText());
            Double fuzExperiencia = Double.parseDouble(experiencia.getText());
        
            if(fuzIdade < 18.0 || fuzIdade > 200){
                 JOptionPane.showMessageDialog(this, "Idade deve estar entre 18 e 200");
            }else{
                if(fuzVelocidade < 0 || fuzVelocidade > 300){
                    JOptionPane.showMessageDialog(this, "Velocidade deve estar entre 0 e 300");
                }else{
                    if(fuzAcidentes < 0 || fuzAcidentes > 100){
                        JOptionPane.showMessageDialog(this, "Quantidade de acidentes deve estar entre 0 e 100");
                    }else{
                        if(fuzExperiencia < 0 || fuzExperiencia > 200){
                            JOptionPane.showMessageDialog(this, "Anos de experiencia devem estar entre 0 e 200");
                        }else{
                            Fuzzificacao fuzzificacao = new Fuzzificacao(fuzIdade, fuzVelocidade, fuzAcidentes, fuzExperiencia);

                            AvaliacaoRegras avaliacaoRegras = new AvaliacaoRegras(
                            fuzzificacao.funcaoPertinenciaIdade(),
                            fuzzificacao.funcaoPertinenciaVelocidade(),
                            fuzzificacao.funcaoPertinenciaAcidentes(),
                            fuzzificacao.funcaoPertinenciaExperiencia());

                            Double valorRisco = avaliacaoRegras.Regras();

                            Risco risco = fuzzificacao.funcaoPertinenciaRisco(valorRisco);
                            String resultado = "Assinar o contrato com esse segurado tem risco:\n" 
                                    + risco.getBaixo()*100 + "% Baixo\n" 
                                    + risco.getMedio()*100 + "% Médio\n" 
                                    + risco.getAlto()*100 + "% Alto";
                            JOptionPane.showMessageDialog(this, resultado);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_decidirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntefaceClassificadorDeSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntefaceClassificadorDeSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntefaceClassificadorDeSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntefaceClassificadorDeSeguros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntefaceClassificadorDeSeguros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acidentes;
    private javax.swing.JButton decidir;
    private javax.swing.JLabel enunciado1;
    private javax.swing.JLabel enunciado2;
    private javax.swing.JTextField experiencia;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel lblacidentes;
    private javax.swing.JLabel lblexperiencia;
    private javax.swing.JLabel lblidade;
    private javax.swing.JLabel lblvelocidade;
    private javax.swing.JLabel questao1;
    private javax.swing.JLabel questao2;
    private javax.swing.JLabel questao3;
    private javax.swing.JLabel questao4;
    private javax.swing.JLabel resposta;
    private javax.swing.JTextField velocidade;
    // End of variables declaration//GEN-END:variables
}
