/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moa2014;

import java.io.IOException;
import java.io.InputStream;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class MOA2014 extends javax.swing.JFrame {
    public static double c1, c2, c3;

    public double getC1() {
        return c1;
    }

    public double getC2() {
        return c2;
    }

    public double getC3() {
        return c3;
    }
    public MOA2014() {
        initComponents();
    }
    
    public int[][] popularMatriz(){
        int[][] matriz = {{0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}};
        matriz[0][0] = Integer.parseInt(this.a00.getText());
        matriz[0][1] = Integer.parseInt(this.a01.getText());
        matriz[0][2] = Integer.parseInt(this.a02.getText());
        matriz[0][3] = Integer.parseInt(this.a03.getText());
        matriz[1][0] = Integer.parseInt(this.a10.getText());
        matriz[1][1] = Integer.parseInt(this.a11.getText());
        matriz[1][2] = Integer.parseInt(this.a12.getText());
        matriz[1][3] = Integer.parseInt(this.a13.getText());
        matriz[2][0] = Integer.parseInt(this.a20.getText());
        matriz[2][1] = Integer.parseInt(this.a21.getText());
        matriz[2][2] = Integer.parseInt(this.a22.getText());
        matriz[2][3] = Integer.parseInt(this.a23.getText());
        matriz[3][0] = Integer.parseInt(this.a30.getText());
        matriz[3][1] = Integer.parseInt(this.a31.getText());
        matriz[3][2] = Integer.parseInt(this.a32.getText());
        matriz[3][3] = Integer.parseInt(this.a33.getText());
        return matriz;
    }
    
    public boolean verificarCustom(){
        HashSet<Integer> inteiros = new HashSet();
        inteiros.add(0);
        inteiros.add(1);
        inteiros.add(2);
        inteiros.add(3);
        inteiros.add(4);
        inteiros.add(5);
        inteiros.add(6);
        inteiros.add(7);
        inteiros.add(8);
        inteiros.add(9);
        inteiros.add(10);
        inteiros.add(11);
        inteiros.add(12);
        inteiros.add(13);
        inteiros.add(14);
        inteiros.add(15);
        try{
            boolean a00 = inteiros.remove(Integer.parseInt(this.a00.getText()));
            boolean a01 =inteiros.remove(Integer.parseInt(this.a01.getText()));
            boolean a02 =inteiros.remove(Integer.parseInt(this.a02.getText()));
            boolean a03 =inteiros.remove(Integer.parseInt(this.a03.getText()));
            boolean a10 = inteiros.remove(Integer.parseInt(this.a10.getText()));
            boolean a11 =inteiros.remove(Integer.parseInt(this.a11.getText()));
            boolean a12 =inteiros.remove(Integer.parseInt(this.a12.getText()));
            boolean a13 =inteiros.remove(Integer.parseInt(this.a13.getText()));
            boolean a20 =inteiros.remove(Integer.parseInt(this.a20.getText()));
            boolean a21 =inteiros.remove(Integer.parseInt(this.a21.getText()));
            boolean a22 =inteiros.remove(Integer.parseInt(this.a22.getText()));
            boolean a23 =inteiros.remove(Integer.parseInt(this.a23.getText()));
            boolean a30 =inteiros.remove(Integer.parseInt(this.a30.getText()));
            boolean a31 =inteiros.remove(Integer.parseInt(this.a31.getText()));
            boolean a32 =inteiros.remove(Integer.parseInt(this.a32.getText()));
            boolean a33 =inteiros.remove(Integer.parseInt(this.a33.getText()));
            if (!(a00 && a01 && a02 && a03 && a10 && a11 && a12 && a13 && a20 && a21 && a22 && a23 && a30 && a31 && a00 && a32 && a33)){
                JOptionPane.showMessageDialog(null, "Existem numeros repetidos ou incorretos!");
                return false;
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Existem numeros repetidos ou incorretos!");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        h1 = new javax.swing.JRadioButton();
        h2 = new javax.swing.JRadioButton();
        h3 = new javax.swing.JRadioButton();
        h4 = new javax.swing.JRadioButton();
        h5 = new javax.swing.JRadioButton();
        c1x = new javax.swing.JTextField();
        c2x = new javax.swing.JTextField();
        c3x = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        custom = new javax.swing.JCheckBox();
        a00 = new javax.swing.JTextField();
        a01 = new javax.swing.JTextField();
        a03 = new javax.swing.JTextField();
        a02 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        a13 = new javax.swing.JTextField();
        a20 = new javax.swing.JTextField();
        a23 = new javax.swing.JTextField();
        a22 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        a30 = new javax.swing.JTextField();
        a31 = new javax.swing.JTextField();
        a21 = new javax.swing.JTextField();
        a33 = new javax.swing.JTextField();
        a32 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("15-Puzzle Solver");

        buttonGroup1.add(h1);
        h1.setText("Heuristica 1");

        buttonGroup1.add(h2);
        h2.setText("Heuristica 2");

        buttonGroup1.add(h3);
        h3.setText("Heuristica 3");
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(h4);
        h4.setText("Heuristica 4");

        buttonGroup1.add(h5);
        h5.setText("Heuristica 5");

        jLabel2.setText("C1");

        jLabel3.setText("C2");

        jLabel4.setText("C3");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Executar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        custom.setText("Matriz Customizada");
        custom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customActionPerformed(evt);
            }
        });

        a00.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a00.setEnabled(false);

        a01.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a01.setEnabled(false);

        a03.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a03.setEnabled(false);

        a02.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a02.setEnabled(false);

        a11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a11.setEnabled(false);

        a12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a12.setEnabled(false);

        a13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a13.setEnabled(false);

        a20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a20.setEnabled(false);

        a23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a23.setEnabled(false);

        a22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a22.setEnabled(false);

        a10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a10.setEnabled(false);

        jTextField12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextField12.setEnabled(false);

        a30.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a30.setEnabled(false);

        a31.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a31.setEnabled(false);

        a21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a21.setEnabled(false);

        a33.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a33.setEnabled(false);

        a32.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        a32.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(h2)
                                    .addComponent(h1)
                                    .addComponent(h3)
                                    .addComponent(h4)
                                    .addComponent(h5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(a00, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(custom)
                                                    .addComponent(a20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(a30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(a31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c1x, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c2x, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c3x, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(206, 206, 206)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a03, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(a32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(a33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h1)
                    .addComponent(custom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h2)
                    .addComponent(a00, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a03, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h3)
                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(h4)
                            .addComponent(c1x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c3x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(a30, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a33, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(h5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (custom.isSelected()){
            if(verificarCustom()){
                int[][] custom = popularMatriz();
                if (h1.isSelected()){
                MOAJAVAPP.main("1", 1, 1, 1, custom);
                }
                else if (h2.isSelected()){
                    MOAJAVAPP.main("2", 1, 1, 1, custom);
                }
                else if (h3.isSelected()){
                    MOAJAVAPP.main("3", 1, 1, 1, custom);

                }
                else if (h4.isSelected()){
                    try{


                        this.c1 = Double.parseDouble(c1x.getText());
                        this.c2 = Double.parseDouble(c2x.getText());
                        this.c3 = Double.parseDouble(c3x.getText());
                        if (this.c1 + this.c2 + this.c3 == 1.00){
                            MOAJAVAPP.main("4", c1, c2, c3, custom);
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Soma dos valores deve ser igual a 1");
                        }
                    }
                    catch(NumberFormatException ex){
                        JOptionPane.showMessageDialog(null, "Valor(es) incorreto(s)! \nUse '.' \nExemplo: 0.25 ; 0.5 ; 0.75 ");
                    }
                }
                else if (h5.isSelected()){
                    MOAJAVAPP.main("5", 1, 1, 1, custom);
                }
            }
        }
        else{
            
        
            if (h1.isSelected()){
                MOAJAVAPP.main("1", 1, 1, 1);
            }
            else if (h2.isSelected()){
                MOAJAVAPP.main("2", 1, 1, 1);
            }
            else if (h3.isSelected()){
                MOAJAVAPP.main("3", 1, 1, 1);

            }
            else if (h4.isSelected()){
                try{


                    this.c1 = Double.parseDouble(c1x.getText());
                    this.c2 = Double.parseDouble(c2x.getText());
                    this.c3 = Double.parseDouble(c3x.getText());
                    if (this.c1 + this.c2 + this.c3 == 1.00){
                        MOAJAVAPP.main("4", c1, c2, c3);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Soma dos valores deve ser igual a 1");
                    }
                }
                catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "Valor(es) incorreto(s)! \nUse '.' \nExemplo: 0.25 ; 0.5 ; 0.75 ");
                }
            }
            else if (h5.isSelected()){
                MOAJAVAPP.main("5", 1, 1, 1);
            }
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h3ActionPerformed

    private void customActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customActionPerformed
        if (custom.isSelected()){
            this.a00.setEnabled(true);
            this.a01.setEnabled(true);
            this.a02.setEnabled(true);
            this.a03.setEnabled(true);
            this.a10.setEnabled(true);
            this.a11.setEnabled(true);
            this.a12.setEnabled(true);
            this.a13.setEnabled(true);
            this.a20.setEnabled(true);
            this.a21.setEnabled(true);
            this.a22.setEnabled(true);
            this.a22.setEnabled(true);
            this.a23.setEnabled(true);
            this.a30.setEnabled(true);
            this.a31.setEnabled(true);
            this.a32.setEnabled(true);
            this.a33.setEnabled(true);

        }
        else{
            this.a00.setEnabled(false);
            this.a01.setEnabled(false);
            this.a02.setEnabled(false);
            this.a03.setEnabled(false);
            this.a10.setEnabled(false);
            this.a11.setEnabled(false);
            this.a12.setEnabled(false);
            this.a13.setEnabled(false);
            this.a20.setEnabled(false);
            this.a21.setEnabled(false);
            this.a22.setEnabled(false);
            this.a22.setEnabled(false);
            this.a23.setEnabled(false);
            this.a30.setEnabled(false);
            this.a31.setEnabled(false);
            this.a32.setEnabled(false);
            this.a33.setEnabled(false);
            this.h1.setEnabled(true);
            this.h2.setEnabled(true);
            this.h3.setEnabled(true);
            this.h4.setEnabled(true);
            this.h5.setEnabled(true);
            this.c1x.setEnabled(true);
            this.c2x.setEnabled(true);
            this.c3x.setEnabled(true);
        }
    }//GEN-LAST:event_customActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MOA2014.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MOA2014.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MOA2014.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MOA2014.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MOA2014().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a00;
    private javax.swing.JTextField a01;
    private javax.swing.JTextField a02;
    private javax.swing.JTextField a03;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a13;
    private javax.swing.JTextField a20;
    private javax.swing.JTextField a21;
    private javax.swing.JTextField a22;
    private javax.swing.JTextField a23;
    private javax.swing.JTextField a30;
    private javax.swing.JTextField a31;
    private javax.swing.JTextField a32;
    private javax.swing.JTextField a33;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c1x;
    private javax.swing.JTextField c2x;
    private javax.swing.JTextField c3x;
    private javax.swing.JCheckBox custom;
    private javax.swing.JRadioButton h1;
    private javax.swing.JRadioButton h2;
    private javax.swing.JRadioButton h3;
    private javax.swing.JRadioButton h4;
    private javax.swing.JRadioButton h5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField12;
    // End of variables declaration//GEN-END:variables
}
